# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x04\x65x00\"\x1a\n\x0b\x43oordinates\x12\x0b\n\x03pos\x18\x01 \x03(\x02\"\x94\x03\n\x04Ship\x12+\n\talignment\x18\x01 \x02(\x0e\x32\x18.ex00.Ship.AlignmentType\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06length\x18\x03 \x02(\x02\x12,\n\nclass_ship\x18\x04 \x02(\x0e\x32\x18.ex00.Ship.ClassShipType\x12\x0c\n\x04size\x18\x05 \x02(\x05\x12\r\n\x05\x61rmed\x18\x06 \x02(\x08\x12%\n\x06oficer\x18\x07 \x03(\x0b\x32\x15.ex00.Ship.OficerType\x1a\x43\n\nOficerType\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x13\n\x0bsecond_name\x18\x02 \x02(\t\x12\x0c\n\x04rank\x18\x03 \x02(\t\"$\n\rAlignmentType\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"d\n\rClassShipType\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\"!\n\x05Ships\x12\x18\n\x04ship\x18\x01 \x03(\x0b\x32\n.ex00.Ship27\n\x05Space\x12.\n\tget_ships\x12\x11.ex00.Coordinates\x1a\n.ex00.Ship\"\x00\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COORDINATES']._serialized_start=20
  _globals['_COORDINATES']._serialized_end=46
  _globals['_SHIP']._serialized_start=49
  _globals['_SHIP']._serialized_end=453
  _globals['_SHIP_OFICERTYPE']._serialized_start=246
  _globals['_SHIP_OFICERTYPE']._serialized_end=313
  _globals['_SHIP_ALIGNMENTTYPE']._serialized_start=315
  _globals['_SHIP_ALIGNMENTTYPE']._serialized_end=351
  _globals['_SHIP_CLASSSHIPTYPE']._serialized_start=353
  _globals['_SHIP_CLASSSHIPTYPE']._serialized_end=453
  _globals['_SHIPS']._serialized_start=455
  _globals['_SHIPS']._serialized_end=488
  _globals['_SPACE']._serialized_start=490
  _globals['_SPACE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
